apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: async-micro-hpa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Ridwan414/async-micro.git
    targetRevision: stag
    path: manifests/hpa

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
