apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: async-micro-load-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Ridwan414/async-micro.git
    targetRevision: HEAD
    path: load-test

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

  revisionHistoryLimit: 3

